services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/ssl:/etc/nginx/ssl:ro
      - ./www/html:/var/www/static
    restart: unless-stopped
    network_mode: host  # 使用host网络模式以访问本机3000端口