services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./master.cnf:/etc/mysql/conf.d/master.cnf
      - ./master-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-replication-net
    restart: unless-stopped

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./slave.cnf:/etc/mysql/conf.d/slave.cnf
      - ./slave-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql-replication-net
    restart: unless-stopped
    depends_on:
      - mysql-master

networks:
  mysql-replication-net:
    external: true
